site_name: DecLog
site_description: "A minimal boilerplate logger for functions."
site_url: "https://josh-read.github.io/declog/"
repo_url: "https://github.com/josh-read/declog"
repo_name: "josh-read/declog"

theme:
  name: "material"

markdown_extensions:
    - pymdownx.snippets:

plugins:
  - mkdocstrings

nav:
  - Home:
    - Overview: README.md
    - About: about.md
  - User Guide:
    - Installation: 'install.md'
    - Basic Usage: 'basic_usage.md'
    - Tutorial: 'tutorial.md'
  - API Reference: 'reference.md'
  - Developer Guide: 'dev_guide.md'